# Generated by Django 5.2.14 on 2026-05-09 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lead_type",
                    models.CharField(
                        choices=[
                            ("PRODUCT_INTEREST", "Interés en producto"),
                            ("CUSTOM_DESIGN", "Diseño personalizado"),
                            ("GENERAL_CONTACT", "Contacto general"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Nuevo"),
                            ("CONTACTED", "Contactado"),
                            ("IN_PROGRESS", "En seguimiento"),
                            ("CLOSED", "Cerrado"),
                            ("DISCARDED", "Descartado"),
                        ],
                        default="NEW",
                        max_length=24,
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("message", models.TextField(blank=True)),
                ("product_name_snapshot", models.CharField(blank=True, max_length=160)),
                ("occasion", models.CharField(blank=True, max_length=160)),
                ("budget_range", models.CharField(blank=True, max_length=120)),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("WHATSAPP", "WhatsApp"),
                            ("EMAIL", "Email"),
                            ("PHONE", "Teléfono"),
                        ],
                        default="WHATSAPP",
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
